### ISSUE TITLE
Enable support for GatsbyJS

### ISSUE THREAD

**Issue by sgeier** [ashthornton/asscroll#18]
Trying to integrate the library into GatsbyJS fails due to the window object undefined during server-side rendering.
Thanks for your help on that.

[=========================== ]   16.871 s 249/253 98% Generating image thumbnails
ReferenceError: window is not defined
    at Object../node_modules/@ashthornton/asscroll/build/asscroll.js (/Users/geier/Projects/webdev/public/render-page.js:1753:4)
    at __webpack_require__ (/Users/geier/Projects/webdev/public/render-page.js:30:30)
    at Module../src/components/app-layout/AppLayout.tsx (/Users/geier/Projects/webdev/public/render-page.js:64087:79)
    at __webpack_require__ (/Users/geier/Projects/webdev/public/render-page.js:30:30)
    at Object../node_modules/gatsby-plugin-layout/wrap-page.js (/Users/geier/Projects/webdev/public/render-page.js:11123:26)
    at __webpack_require__ (/Users/geier/Projects/webdev/public/render-page.js:30:30)
    at Object../node_modules/gatsby-plugin-layout/gatsby-ssr.js (/Users/geier/Projects/webdev/public/render-page.js:11100:27)
    at __webpack_require__ (/Users/geier/Projects/webdev/public/render-page.js:30:30)
    at Object../.cache/api-runner-ssr.js (/Users/geier/Projects/webdev/public/render-page.js:139:11)
    at __webpack_require__ (/Users/geier/Projects/webdev/public/render-page.js:30:30)
    at Module../.cache/develop-static-entry.js (/Users/geier/Projects/webdev/public/render-page.js:468:73)
    at __webpack_require__ (/Users/geier/Projects/webdev/public/render-page.js:30:30)
    at /Users/geier/Projects/webdev/public/render-page.js:94:18
    at /Users/geier/Projects/webdev/public/render-page.js:97:10
    at webpackUniversalModuleDefinition (/Users/geier/Projects/webdev/public/render-page.js:3:20)

There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: window is not defined

   8 | 	else
   9 | 		root["ASScroll"] = factory();
> 10 | })(window, function() {
     |  ^
  11 | return /******/ (function(modules) { // webpackBootstrap
  12 | /******/ 	// The module cache
  13 | /******/ 	var installedModules = {};

  WebpackError: ReferenceError: window is not defined

  - asscroll.js:10
    node_modules/@ashthornton/asscroll/build/asscroll.js:10:2

**Comment by ashthornton** [comment]
Hi @sgeier, looking at the Gatsby docs it suggests trying this: https://www.gatsbyjs.com/docs/debugging-html-builds/#how-to-check-if-window-is-defined

Does that method work for you?
